/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios/index'
import { Route as AuthenticatedPacientesIndexRouteImport } from './routes/_authenticated/pacientes/index'
import { Route as AuthenticatedFaturamentosIndexRouteImport } from './routes/_authenticated/faturamentos/index'
import { Route as AuthenticatedAutorizacoesIndexRouteImport } from './routes/_authenticated/autorizacoes/index'
import { Route as AuthenticatedPacientesNovoRouteImport } from './routes/_authenticated/pacientes/novo'
import { Route as AuthenticatedPacientesIdRouteImport } from './routes/_authenticated/pacientes/$id'
import { Route as AuthenticatedFaturamentosEmpresaIdRouteImport } from './routes/_authenticated/faturamentos/$empresaId'
import { Route as AuthenticatedCadastrosUbsRouteImport } from './routes/_authenticated/cadastros/ubs'
import { Route as AuthenticatedCadastrosTerritorioRouteImport } from './routes/_authenticated/cadastros/territorio'
import { Route as AuthenticatedCadastrosProfissionaisRouteImport } from './routes/_authenticated/cadastros/profissionais'
import { Route as AuthenticatedCadastrosProcedimentosRouteImport } from './routes/_authenticated/cadastros/procedimentos'
import { Route as AuthenticatedCadastrosEmpresasRouteImport } from './routes/_authenticated/cadastros/empresas'
import { Route as AuthenticatedAutorizacoesNovaRouteImport } from './routes/_authenticated/autorizacoes/nova'
import { Route as AuthenticatedAutorizacoesIdRouteImport } from './routes/_authenticated/autorizacoes/$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAcrescimosNovoRouteImport } from './routes/_authenticated/acrescimos/novo'
import { Route as AuthenticatedAutorizacoesIdEditarRouteImport } from './routes/_authenticated/autorizacoes/$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientesIndexRoute =
  AuthenticatedPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFaturamentosIndexRoute =
  AuthenticatedFaturamentosIndexRouteImport.update({
    id: '/faturamentos/',
    path: '/faturamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutorizacoesIndexRoute =
  AuthenticatedAutorizacoesIndexRouteImport.update({
    id: '/autorizacoes/',
    path: '/autorizacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientesNovoRoute =
  AuthenticatedPacientesNovoRouteImport.update({
    id: '/pacientes/novo',
    path: '/pacientes/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientesIdRoute =
  AuthenticatedPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFaturamentosEmpresaIdRoute =
  AuthenticatedFaturamentosEmpresaIdRouteImport.update({
    id: '/faturamentos/$empresaId',
    path: '/faturamentos/$empresaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosUbsRoute =
  AuthenticatedCadastrosUbsRouteImport.update({
    id: '/cadastros/ubs',
    path: '/cadastros/ubs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosTerritorioRoute =
  AuthenticatedCadastrosTerritorioRouteImport.update({
    id: '/cadastros/territorio',
    path: '/cadastros/territorio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosProfissionaisRoute =
  AuthenticatedCadastrosProfissionaisRouteImport.update({
    id: '/cadastros/profissionais',
    path: '/cadastros/profissionais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosProcedimentosRoute =
  AuthenticatedCadastrosProcedimentosRouteImport.update({
    id: '/cadastros/procedimentos',
    path: '/cadastros/procedimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosEmpresasRoute =
  AuthenticatedCadastrosEmpresasRouteImport.update({
    id: '/cadastros/empresas',
    path: '/cadastros/empresas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutorizacoesNovaRoute =
  AuthenticatedAutorizacoesNovaRouteImport.update({
    id: '/autorizacoes/nova',
    path: '/autorizacoes/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutorizacoesIdRoute =
  AuthenticatedAutorizacoesIdRouteImport.update({
    id: '/autorizacoes/$id',
    path: '/autorizacoes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcrescimosNovoRoute =
  AuthenticatedAcrescimosNovoRouteImport.update({
    id: '/acrescimos/novo',
    path: '/acrescimos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutorizacoesIdEditarRoute =
  AuthenticatedAutorizacoesIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedAutorizacoesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/acrescimos/novo': typeof AuthenticatedAcrescimosNovoRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/autorizacoes/$id': typeof AuthenticatedAutorizacoesIdRouteWithChildren
  '/autorizacoes/nova': typeof AuthenticatedAutorizacoesNovaRoute
  '/cadastros/empresas': typeof AuthenticatedCadastrosEmpresasRoute
  '/cadastros/procedimentos': typeof AuthenticatedCadastrosProcedimentosRoute
  '/cadastros/profissionais': typeof AuthenticatedCadastrosProfissionaisRoute
  '/cadastros/territorio': typeof AuthenticatedCadastrosTerritorioRoute
  '/cadastros/ubs': typeof AuthenticatedCadastrosUbsRoute
  '/faturamentos/$empresaId': typeof AuthenticatedFaturamentosEmpresaIdRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/pacientes/novo': typeof AuthenticatedPacientesNovoRoute
  '/autorizacoes/': typeof AuthenticatedAutorizacoesIndexRoute
  '/faturamentos/': typeof AuthenticatedFaturamentosIndexRoute
  '/pacientes/': typeof AuthenticatedPacientesIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/autorizacoes/$id/editar': typeof AuthenticatedAutorizacoesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/acrescimos/novo': typeof AuthenticatedAcrescimosNovoRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/autorizacoes/$id': typeof AuthenticatedAutorizacoesIdRouteWithChildren
  '/autorizacoes/nova': typeof AuthenticatedAutorizacoesNovaRoute
  '/cadastros/empresas': typeof AuthenticatedCadastrosEmpresasRoute
  '/cadastros/procedimentos': typeof AuthenticatedCadastrosProcedimentosRoute
  '/cadastros/profissionais': typeof AuthenticatedCadastrosProfissionaisRoute
  '/cadastros/territorio': typeof AuthenticatedCadastrosTerritorioRoute
  '/cadastros/ubs': typeof AuthenticatedCadastrosUbsRoute
  '/faturamentos/$empresaId': typeof AuthenticatedFaturamentosEmpresaIdRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/pacientes/novo': typeof AuthenticatedPacientesNovoRoute
  '/autorizacoes': typeof AuthenticatedAutorizacoesIndexRoute
  '/faturamentos': typeof AuthenticatedFaturamentosIndexRoute
  '/pacientes': typeof AuthenticatedPacientesIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/autorizacoes/$id/editar': typeof AuthenticatedAutorizacoesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/acrescimos/novo': typeof AuthenticatedAcrescimosNovoRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/autorizacoes/$id': typeof AuthenticatedAutorizacoesIdRouteWithChildren
  '/_authenticated/autorizacoes/nova': typeof AuthenticatedAutorizacoesNovaRoute
  '/_authenticated/cadastros/empresas': typeof AuthenticatedCadastrosEmpresasRoute
  '/_authenticated/cadastros/procedimentos': typeof AuthenticatedCadastrosProcedimentosRoute
  '/_authenticated/cadastros/profissionais': typeof AuthenticatedCadastrosProfissionaisRoute
  '/_authenticated/cadastros/territorio': typeof AuthenticatedCadastrosTerritorioRoute
  '/_authenticated/cadastros/ubs': typeof AuthenticatedCadastrosUbsRoute
  '/_authenticated/faturamentos/$empresaId': typeof AuthenticatedFaturamentosEmpresaIdRoute
  '/_authenticated/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/_authenticated/pacientes/novo': typeof AuthenticatedPacientesNovoRoute
  '/_authenticated/autorizacoes/': typeof AuthenticatedAutorizacoesIndexRoute
  '/_authenticated/faturamentos/': typeof AuthenticatedFaturamentosIndexRoute
  '/_authenticated/pacientes/': typeof AuthenticatedPacientesIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/autorizacoes/$id/editar': typeof AuthenticatedAutorizacoesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/acrescimos/novo'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/autorizacoes/$id'
    | '/autorizacoes/nova'
    | '/cadastros/empresas'
    | '/cadastros/procedimentos'
    | '/cadastros/profissionais'
    | '/cadastros/territorio'
    | '/cadastros/ubs'
    | '/faturamentos/$empresaId'
    | '/pacientes/$id'
    | '/pacientes/novo'
    | '/autorizacoes/'
    | '/faturamentos/'
    | '/pacientes/'
    | '/relatorios/'
    | '/autorizacoes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/acrescimos/novo'
    | '/admin/logs'
    | '/admin/usuarios'
    | '/autorizacoes/$id'
    | '/autorizacoes/nova'
    | '/cadastros/empresas'
    | '/cadastros/procedimentos'
    | '/cadastros/profissionais'
    | '/cadastros/territorio'
    | '/cadastros/ubs'
    | '/faturamentos/$empresaId'
    | '/pacientes/$id'
    | '/pacientes/novo'
    | '/autorizacoes'
    | '/faturamentos'
    | '/pacientes'
    | '/relatorios'
    | '/autorizacoes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/acrescimos/novo'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/autorizacoes/$id'
    | '/_authenticated/autorizacoes/nova'
    | '/_authenticated/cadastros/empresas'
    | '/_authenticated/cadastros/procedimentos'
    | '/_authenticated/cadastros/profissionais'
    | '/_authenticated/cadastros/territorio'
    | '/_authenticated/cadastros/ubs'
    | '/_authenticated/faturamentos/$empresaId'
    | '/_authenticated/pacientes/$id'
    | '/_authenticated/pacientes/novo'
    | '/_authenticated/autorizacoes/'
    | '/_authenticated/faturamentos/'
    | '/_authenticated/pacientes/'
    | '/_authenticated/relatorios/'
    | '/_authenticated/autorizacoes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacientes/': {
      id: '/_authenticated/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faturamentos/': {
      id: '/_authenticated/faturamentos/'
      path: '/faturamentos'
      fullPath: '/faturamentos/'
      preLoaderRoute: typeof AuthenticatedFaturamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autorizacoes/': {
      id: '/_authenticated/autorizacoes/'
      path: '/autorizacoes'
      fullPath: '/autorizacoes/'
      preLoaderRoute: typeof AuthenticatedAutorizacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacientes/novo': {
      id: '/_authenticated/pacientes/novo'
      path: '/pacientes/novo'
      fullPath: '/pacientes/novo'
      preLoaderRoute: typeof AuthenticatedPacientesNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacientes/$id': {
      id: '/_authenticated/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedPacientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faturamentos/$empresaId': {
      id: '/_authenticated/faturamentos/$empresaId'
      path: '/faturamentos/$empresaId'
      fullPath: '/faturamentos/$empresaId'
      preLoaderRoute: typeof AuthenticatedFaturamentosEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/ubs': {
      id: '/_authenticated/cadastros/ubs'
      path: '/cadastros/ubs'
      fullPath: '/cadastros/ubs'
      preLoaderRoute: typeof AuthenticatedCadastrosUbsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/territorio': {
      id: '/_authenticated/cadastros/territorio'
      path: '/cadastros/territorio'
      fullPath: '/cadastros/territorio'
      preLoaderRoute: typeof AuthenticatedCadastrosTerritorioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/profissionais': {
      id: '/_authenticated/cadastros/profissionais'
      path: '/cadastros/profissionais'
      fullPath: '/cadastros/profissionais'
      preLoaderRoute: typeof AuthenticatedCadastrosProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/procedimentos': {
      id: '/_authenticated/cadastros/procedimentos'
      path: '/cadastros/procedimentos'
      fullPath: '/cadastros/procedimentos'
      preLoaderRoute: typeof AuthenticatedCadastrosProcedimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/empresas': {
      id: '/_authenticated/cadastros/empresas'
      path: '/cadastros/empresas'
      fullPath: '/cadastros/empresas'
      preLoaderRoute: typeof AuthenticatedCadastrosEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autorizacoes/nova': {
      id: '/_authenticated/autorizacoes/nova'
      path: '/autorizacoes/nova'
      fullPath: '/autorizacoes/nova'
      preLoaderRoute: typeof AuthenticatedAutorizacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autorizacoes/$id': {
      id: '/_authenticated/autorizacoes/$id'
      path: '/autorizacoes/$id'
      fullPath: '/autorizacoes/$id'
      preLoaderRoute: typeof AuthenticatedAutorizacoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acrescimos/novo': {
      id: '/_authenticated/acrescimos/novo'
      path: '/acrescimos/novo'
      fullPath: '/acrescimos/novo'
      preLoaderRoute: typeof AuthenticatedAcrescimosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autorizacoes/$id/editar': {
      id: '/_authenticated/autorizacoes/$id/editar'
      path: '/editar'
      fullPath: '/autorizacoes/$id/editar'
      preLoaderRoute: typeof AuthenticatedAutorizacoesIdEditarRouteImport
      parentRoute: typeof AuthenticatedAutorizacoesIdRoute
    }
  }
}

interface AuthenticatedAutorizacoesIdRouteChildren {
  AuthenticatedAutorizacoesIdEditarRoute: typeof AuthenticatedAutorizacoesIdEditarRoute
}

const AuthenticatedAutorizacoesIdRouteChildren: AuthenticatedAutorizacoesIdRouteChildren =
  {
    AuthenticatedAutorizacoesIdEditarRoute:
      AuthenticatedAutorizacoesIdEditarRoute,
  }

const AuthenticatedAutorizacoesIdRouteWithChildren =
  AuthenticatedAutorizacoesIdRoute._addFileChildren(
    AuthenticatedAutorizacoesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAcrescimosNovoRoute: typeof AuthenticatedAcrescimosNovoRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAutorizacoesIdRoute: typeof AuthenticatedAutorizacoesIdRouteWithChildren
  AuthenticatedAutorizacoesNovaRoute: typeof AuthenticatedAutorizacoesNovaRoute
  AuthenticatedCadastrosEmpresasRoute: typeof AuthenticatedCadastrosEmpresasRoute
  AuthenticatedCadastrosProcedimentosRoute: typeof AuthenticatedCadastrosProcedimentosRoute
  AuthenticatedCadastrosProfissionaisRoute: typeof AuthenticatedCadastrosProfissionaisRoute
  AuthenticatedCadastrosTerritorioRoute: typeof AuthenticatedCadastrosTerritorioRoute
  AuthenticatedCadastrosUbsRoute: typeof AuthenticatedCadastrosUbsRoute
  AuthenticatedFaturamentosEmpresaIdRoute: typeof AuthenticatedFaturamentosEmpresaIdRoute
  AuthenticatedPacientesIdRoute: typeof AuthenticatedPacientesIdRoute
  AuthenticatedPacientesNovoRoute: typeof AuthenticatedPacientesNovoRoute
  AuthenticatedAutorizacoesIndexRoute: typeof AuthenticatedAutorizacoesIndexRoute
  AuthenticatedFaturamentosIndexRoute: typeof AuthenticatedFaturamentosIndexRoute
  AuthenticatedPacientesIndexRoute: typeof AuthenticatedPacientesIndexRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAcrescimosNovoRoute: AuthenticatedAcrescimosNovoRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAutorizacoesIdRoute:
    AuthenticatedAutorizacoesIdRouteWithChildren,
  AuthenticatedAutorizacoesNovaRoute: AuthenticatedAutorizacoesNovaRoute,
  AuthenticatedCadastrosEmpresasRoute: AuthenticatedCadastrosEmpresasRoute,
  AuthenticatedCadastrosProcedimentosRoute:
    AuthenticatedCadastrosProcedimentosRoute,
  AuthenticatedCadastrosProfissionaisRoute:
    AuthenticatedCadastrosProfissionaisRoute,
  AuthenticatedCadastrosTerritorioRoute: AuthenticatedCadastrosTerritorioRoute,
  AuthenticatedCadastrosUbsRoute: AuthenticatedCadastrosUbsRoute,
  AuthenticatedFaturamentosEmpresaIdRoute:
    AuthenticatedFaturamentosEmpresaIdRoute,
  AuthenticatedPacientesIdRoute: AuthenticatedPacientesIdRoute,
  AuthenticatedPacientesNovoRoute: AuthenticatedPacientesNovoRoute,
  AuthenticatedAutorizacoesIndexRoute: AuthenticatedAutorizacoesIndexRoute,
  AuthenticatedFaturamentosIndexRoute: AuthenticatedFaturamentosIndexRoute,
  AuthenticatedPacientesIndexRoute: AuthenticatedPacientesIndexRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
