/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSaudeIndexRouteImport } from './routes/_authenticated/saude/index'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/dashboard'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/relatorios/index'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/pacientes/index'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/index'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/index'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/pacientes/novo'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/pacientes/$id'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/$empresaId'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/cadastros/ubs'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/cadastros/territorio'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/cadastros/profissionais'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/cadastros/procedimentos'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/cadastros/empresas'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/nova'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/admin/usuarios'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/admin/logs'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/acrescimos/novo'
import { Route as AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRouteImport } from './routes/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSaudeIndexRoute = AuthenticatedSaudeIndexRouteImport.update({
  id: '/saude/',
  path: '/saude/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteImport.update({
    id: '/saude/regulacao/autorizacao-exames',
    path: '/saude/regulacao/autorizacao-exames',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRouteImport.update(
    {
      id: '/relatorios/',
      path: '/relatorios/',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRouteImport.update(
    {
      id: '/faturamentos/',
      path: '/faturamentos/',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRouteImport.update(
    {
      id: '/autorizacoes/',
      path: '/autorizacoes/',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRouteImport.update({
    id: '/pacientes/novo',
    path: '/pacientes/novo',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRouteImport.update(
    {
      id: '/faturamentos/$empresaId',
      path: '/faturamentos/$empresaId',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRouteImport.update({
    id: '/cadastros/ubs',
    path: '/cadastros/ubs',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRouteImport.update(
    {
      id: '/cadastros/territorio',
      path: '/cadastros/territorio',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRouteImport.update(
    {
      id: '/cadastros/profissionais',
      path: '/cadastros/profissionais',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRouteImport.update(
    {
      id: '/cadastros/procedimentos',
      path: '/cadastros/procedimentos',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRouteImport.update(
    {
      id: '/cadastros/empresas',
      path: '/cadastros/empresas',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRouteImport.update(
    {
      id: '/autorizacoes/nova',
      path: '/autorizacoes/nova',
      getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
    } as any,
  )
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteImport.update({
    id: '/autorizacoes/$id',
    path: '/autorizacoes/$id',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRouteImport.update({
    id: '/admin/logs',
    path: '/admin/logs',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRouteImport.update({
    id: '/acrescimos/novo',
    path: '/acrescimos/novo',
    getParentRoute: () => AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute,
  } as any)
const AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRouteImport.update(
    {
      id: '/editar',
      path: '/editar',
      getParentRoute: () =>
        AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/saude/': typeof AuthenticatedSaudeIndexRoute
  '/saude/regulacao/autorizacao-exames': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteWithChildren
  '/saude/regulacao/autorizacao-exames/dashboard': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute
  '/saude/regulacao/autorizacao-exames/acrescimos/novo': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute
  '/saude/regulacao/autorizacao-exames/admin/logs': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute
  '/saude/regulacao/autorizacao-exames/admin/usuarios': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute
  '/saude/regulacao/autorizacao-exames/autorizacoes/$id': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteWithChildren
  '/saude/regulacao/autorizacao-exames/autorizacoes/nova': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute
  '/saude/regulacao/autorizacao-exames/cadastros/empresas': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute
  '/saude/regulacao/autorizacao-exames/cadastros/procedimentos': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute
  '/saude/regulacao/autorizacao-exames/cadastros/profissionais': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute
  '/saude/regulacao/autorizacao-exames/cadastros/territorio': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute
  '/saude/regulacao/autorizacao-exames/cadastros/ubs': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute
  '/saude/regulacao/autorizacao-exames/faturamentos/$empresaId': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute
  '/saude/regulacao/autorizacao-exames/pacientes/$id': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute
  '/saude/regulacao/autorizacao-exames/pacientes/novo': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute
  '/saude/regulacao/autorizacao-exames/autorizacoes/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute
  '/saude/regulacao/autorizacao-exames/faturamentos/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute
  '/saude/regulacao/autorizacao-exames/pacientes/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute
  '/saude/regulacao/autorizacao-exames/relatorios/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute
  '/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/saude': typeof AuthenticatedSaudeIndexRoute
  '/saude/regulacao/autorizacao-exames': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteWithChildren
  '/saude/regulacao/autorizacao-exames/dashboard': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute
  '/saude/regulacao/autorizacao-exames/acrescimos/novo': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute
  '/saude/regulacao/autorizacao-exames/admin/logs': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute
  '/saude/regulacao/autorizacao-exames/admin/usuarios': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute
  '/saude/regulacao/autorizacao-exames/autorizacoes/$id': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteWithChildren
  '/saude/regulacao/autorizacao-exames/autorizacoes/nova': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute
  '/saude/regulacao/autorizacao-exames/cadastros/empresas': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute
  '/saude/regulacao/autorizacao-exames/cadastros/procedimentos': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute
  '/saude/regulacao/autorizacao-exames/cadastros/profissionais': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute
  '/saude/regulacao/autorizacao-exames/cadastros/territorio': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute
  '/saude/regulacao/autorizacao-exames/cadastros/ubs': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute
  '/saude/regulacao/autorizacao-exames/faturamentos/$empresaId': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute
  '/saude/regulacao/autorizacao-exames/pacientes/$id': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute
  '/saude/regulacao/autorizacao-exames/pacientes/novo': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute
  '/saude/regulacao/autorizacao-exames/autorizacoes': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute
  '/saude/regulacao/autorizacao-exames/faturamentos': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute
  '/saude/regulacao/autorizacao-exames/pacientes': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute
  '/saude/regulacao/autorizacao-exames/relatorios': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute
  '/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/saude/': typeof AuthenticatedSaudeIndexRoute
  '/_authenticated/saude/regulacao/autorizacao-exames': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteWithChildren
  '/_authenticated/saude/regulacao/autorizacao-exames/dashboard': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/acrescimos/novo': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/admin/logs': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/admin/usuarios': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteWithChildren
  '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/nova': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/empresas': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/procedimentos': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/profissionais': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/territorio': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/ubs': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/$empresaId': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/$id': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/novo': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/relatorios/': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute
  '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar': typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/saude/'
    | '/saude/regulacao/autorizacao-exames'
    | '/saude/regulacao/autorizacao-exames/dashboard'
    | '/saude/regulacao/autorizacao-exames/acrescimos/novo'
    | '/saude/regulacao/autorizacao-exames/admin/logs'
    | '/saude/regulacao/autorizacao-exames/admin/usuarios'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/$id'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/nova'
    | '/saude/regulacao/autorizacao-exames/cadastros/empresas'
    | '/saude/regulacao/autorizacao-exames/cadastros/procedimentos'
    | '/saude/regulacao/autorizacao-exames/cadastros/profissionais'
    | '/saude/regulacao/autorizacao-exames/cadastros/territorio'
    | '/saude/regulacao/autorizacao-exames/cadastros/ubs'
    | '/saude/regulacao/autorizacao-exames/faturamentos/$empresaId'
    | '/saude/regulacao/autorizacao-exames/pacientes/$id'
    | '/saude/regulacao/autorizacao-exames/pacientes/novo'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/'
    | '/saude/regulacao/autorizacao-exames/faturamentos/'
    | '/saude/regulacao/autorizacao-exames/pacientes/'
    | '/saude/regulacao/autorizacao-exames/relatorios/'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/saude'
    | '/saude/regulacao/autorizacao-exames'
    | '/saude/regulacao/autorizacao-exames/dashboard'
    | '/saude/regulacao/autorizacao-exames/acrescimos/novo'
    | '/saude/regulacao/autorizacao-exames/admin/logs'
    | '/saude/regulacao/autorizacao-exames/admin/usuarios'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/$id'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/nova'
    | '/saude/regulacao/autorizacao-exames/cadastros/empresas'
    | '/saude/regulacao/autorizacao-exames/cadastros/procedimentos'
    | '/saude/regulacao/autorizacao-exames/cadastros/profissionais'
    | '/saude/regulacao/autorizacao-exames/cadastros/territorio'
    | '/saude/regulacao/autorizacao-exames/cadastros/ubs'
    | '/saude/regulacao/autorizacao-exames/faturamentos/$empresaId'
    | '/saude/regulacao/autorizacao-exames/pacientes/$id'
    | '/saude/regulacao/autorizacao-exames/pacientes/novo'
    | '/saude/regulacao/autorizacao-exames/autorizacoes'
    | '/saude/regulacao/autorizacao-exames/faturamentos'
    | '/saude/regulacao/autorizacao-exames/pacientes'
    | '/saude/regulacao/autorizacao-exames/relatorios'
    | '/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/saude/'
    | '/_authenticated/saude/regulacao/autorizacao-exames'
    | '/_authenticated/saude/regulacao/autorizacao-exames/dashboard'
    | '/_authenticated/saude/regulacao/autorizacao-exames/acrescimos/novo'
    | '/_authenticated/saude/regulacao/autorizacao-exames/admin/logs'
    | '/_authenticated/saude/regulacao/autorizacao-exames/admin/usuarios'
    | '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id'
    | '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/nova'
    | '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/empresas'
    | '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/procedimentos'
    | '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/profissionais'
    | '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/territorio'
    | '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/ubs'
    | '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/$empresaId'
    | '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/$id'
    | '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/novo'
    | '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/'
    | '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/'
    | '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/'
    | '/_authenticated/saude/regulacao/autorizacao-exames/relatorios/'
    | '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saude/': {
      id: '/_authenticated/saude/'
      path: '/saude'
      fullPath: '/saude/'
      preLoaderRoute: typeof AuthenticatedSaudeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames'
      path: '/saude/regulacao/autorizacao-exames'
      fullPath: '/saude/regulacao/autorizacao-exames'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/dashboard': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/dashboard'
      path: '/dashboard'
      fullPath: '/saude/regulacao/autorizacao-exames/dashboard'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/relatorios/': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/relatorios/'
      path: '/relatorios'
      fullPath: '/saude/regulacao/autorizacao-exames/relatorios/'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/'
      path: '/pacientes'
      fullPath: '/saude/regulacao/autorizacao-exames/pacientes/'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/'
      path: '/faturamentos'
      fullPath: '/saude/regulacao/autorizacao-exames/faturamentos/'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/'
      path: '/autorizacoes'
      fullPath: '/saude/regulacao/autorizacao-exames/autorizacoes/'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/novo': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/novo'
      path: '/pacientes/novo'
      fullPath: '/saude/regulacao/autorizacao-exames/pacientes/novo'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/$id': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/saude/regulacao/autorizacao-exames/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/$empresaId': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/faturamentos/$empresaId'
      path: '/faturamentos/$empresaId'
      fullPath: '/saude/regulacao/autorizacao-exames/faturamentos/$empresaId'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/ubs': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/ubs'
      path: '/cadastros/ubs'
      fullPath: '/saude/regulacao/autorizacao-exames/cadastros/ubs'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/territorio': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/territorio'
      path: '/cadastros/territorio'
      fullPath: '/saude/regulacao/autorizacao-exames/cadastros/territorio'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/profissionais': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/profissionais'
      path: '/cadastros/profissionais'
      fullPath: '/saude/regulacao/autorizacao-exames/cadastros/profissionais'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/procedimentos': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/procedimentos'
      path: '/cadastros/procedimentos'
      fullPath: '/saude/regulacao/autorizacao-exames/cadastros/procedimentos'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/empresas': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/cadastros/empresas'
      path: '/cadastros/empresas'
      fullPath: '/saude/regulacao/autorizacao-exames/cadastros/empresas'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/nova': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/nova'
      path: '/autorizacoes/nova'
      fullPath: '/saude/regulacao/autorizacao-exames/autorizacoes/nova'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id'
      path: '/autorizacoes/$id'
      fullPath: '/saude/regulacao/autorizacao-exames/autorizacoes/$id'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/admin/usuarios': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/saude/regulacao/autorizacao-exames/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/admin/logs': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/admin/logs'
      path: '/admin/logs'
      fullPath: '/saude/regulacao/autorizacao-exames/admin/logs'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/acrescimos/novo': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/acrescimos/novo'
      path: '/acrescimos/novo'
      fullPath: '/saude/regulacao/autorizacao-exames/acrescimos/novo'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute
    }
    '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar': {
      id: '/_authenticated/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar'
      path: '/editar'
      fullPath: '/saude/regulacao/autorizacao-exames/autorizacoes/$id/editar'
      preLoaderRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRouteImport
      parentRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRoute
    }
  }
}

interface AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteChildren {
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute
}

const AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteChildren: AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteChildren =
  {
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdEditarRoute,
  }

const AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteWithChildren =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRoute._addFileChildren(
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteChildren,
  )

interface AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteChildren {
  AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteWithChildren
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute
}

const AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteChildren: AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteChildren =
  {
    AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesDashboardRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAcrescimosNovoRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminLogsRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAdminUsuariosRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIdRouteWithChildren,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesNovaRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosEmpresasRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProcedimentosRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosProfissionaisRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosTerritorioRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesCadastrosUbsRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosEmpresaIdRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIdRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesNovoRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesAutorizacoesIndexRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesFaturamentosIndexRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesPacientesIndexRoute,
    AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute:
      AuthenticatedSaudeRegulacaoAutorizacaoExamesRelatoriosIndexRoute,
  }

const AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteWithChildren =
  AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute._addFileChildren(
    AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSaudeIndexRoute: typeof AuthenticatedSaudeIndexRoute
  AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute: typeof AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSaudeIndexRoute: AuthenticatedSaudeIndexRoute,
  AuthenticatedSaudeRegulacaoAutorizacaoExamesRoute:
    AuthenticatedSaudeRegulacaoAutorizacaoExamesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
